### ISSUE TITLE
Follow OS theme

### ISSUE THREAD

**Issue by xmha97** [wh201906/SerialTest#29]
Please add the dark theme to this app.

**Comment by wh201906** [comment]
It does have dark theme.
1. Go to "settings"
![图片](https://github.com/wh201906/SerialTest/assets/62299611/a3bf8950-c2fa-46ce-9bef-e8ce599462c3)
2. Select "Dark" in Appearance->Theme
![图片](https://github.com/wh201906/SerialTest/assets/62299611/94108522-cb58-48b0-a33c-698a731ad30c)
3. Click "Set" behind the Theme selector
![图片](https://github.com/wh201906/SerialTest/assets/62299611/e0d61e85-af3e-402f-bc24-0f99e89a45ee)
4. Restart the app
![图片](https://github.com/wh201906/SerialTest/assets/62299611/66ac1d90-68c7-4331-b31c-7936b525f4bf)

**Comment by xmha97** [comment]
Thanks, now I need another feature:
- Please follow the system theme.

Like other apps:
![Screenshot_2023-05-19-02-24-27-106_de.mm20.launcher2.release.jpg](https://github.com/wh201906/SerialTest/assets/23485114/06ae0b22-6e3a-404d-9400-5b9540eefe26)
Please add the "System" item.
![Screenshot_2023-05-19-02-26-09-964_priv.wh201906.serialtest.jpg](https://github.com/wh201906/SerialTest/assets/23485114/a95ac8ce-d191-4a71-b529-4bb64ea22893)

**Comment by wh201906** [comment]
It might be a little bit hard to implement it on Qt5. I'll try it when I'm free.

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by xmha97** [comment]
Please change "(None)" to "Follow system"
It works on Ubuntu fine.

![Screenshot from 2023-06-11 15-37-12](https://github.com/wh201906/SerialTest/assets/23485114/348b8db3-1c7a-4a5e-b1c5-5a7f56aa2a1f)

![Screenshot from 2023-06-11 15-38-20](https://github.com/wh201906/SerialTest/assets/23485114/da6445ef-2c9b-45e9-8ae2-f518d475e089)

**Comment by wh201906** [comment]
@xmha97 It's a cross-platform app and the behavior is not the same on different platforms. So I think it's not good to change the `(None)` to `Follow System`.

**Comment by wh201906** [comment]
Plus, I think I might add more themes in the future, for both dark style and light style. However, users cannot choose which dark style to use with a single `Follow System` option, when the system is in dark mode. 
Users can change the theme without restarting the app now (see 4d15a2fa4833201a8c33c995f05113ed64f5c795 and 7b3dccb753880fbbbeae32d0113625aad90c46f5). So I guess the feature is not so necessary now?

**Comment by xmha97** [comment]
Thanks for the new version.

**Comment by xmha97** [comment]
Android app does not follow OS theme, please reopen this issue.

**Comment by wh201906** [comment]
Sorry but I don't want to add this feature for these reasons:
1. As I mentioned in https://github.com/wh201906/SerialTest/issues/29#issuecomment-1586198310, "Follow OS theme" is ambiguous when there are more than one dark theme. 
2. I guess you want this feature because its inconvenient for users to change the theme before V0.3.2. That's true, as they have to restart the app to do so. However it's less necessary now because I have removed the limitation. Following OS theme is good for the user experience, but it might cost a lot of time for me to implement this because it's a Qt app.
3. As you said in https://github.com/wh201906/SerialTest/issues/29#issuecomment-1586140024, the default theme does follow the OS theme on Ubuntu.
